import { Widget, DeviceConfig, Screen } from '../types';

export function generateEmbeddedCode(screens: Screen[], device: DeviceConfig): string {
    const includes = `
#include <TFT_eSPI.h>
#include <SPI.h>

TFT_eSPI tft = TFT_eSPI();
`;

    const setup = `
void setup() {
  Serial.begin(115200);
  tft.init();
  tft.setRotation(1);
  tft.fillScreen(TFT_BLACK);
  
  // Initialize UI
  drawUI();
}
`;

    const loop = `
void loop() {
  // Handle touch input and update widgets
  delay(50);
}
`;

    const drawUI = `
void drawUI() {
  tft.fillScreen(TFT_BLACK);
  
${widgets.map(widget => generateWidgetCode(widget)).join('\n')}
}
`;

    return includes + setup + loop + drawUI;
}

function generateWidgetCode(widget: Widget): string {
    const { type, position, size, properties } = widget;

    switch (type) {
        case 'label':
            return `  // Label Widget
  tft.setTextColor(${hexToRgb565(properties.color || '#FFFFFF')});
  tft.setTextSize(${Math.round((properties.fontSize || 14) / 8)});
  tft.setCursor(${position.x}, ${position.y});
  tft.print("${properties.text || 'Label'}");`;

        case 'button':
            return `  // Button Widget
  tft.fillRoundRect(${position.x}, ${position.y}, ${size.width}, ${size.height}, ${properties.borderRadius || 0}, ${hexToRgb565(properties.backgroundColor || '#0EA5E9')});
  tft.setTextColor(${hexToRgb565(properties.color || '#FFFFFF')});
  tft.setTextSize(${Math.round((properties.fontSize || 14) / 8)});
  tft.setCursor(${position.x + 10}, ${position.y + size.height / 2 - 8});
  tft.print("${properties.text || 'Button'}");`;

        case 'gauge':
            return `  // Gauge Widget
  int gaugeValue = ${properties.value || 0};
  int gaugeMax = ${properties.max || 100};
  int angle = map(gaugeValue, 0, gaugeMax, 0, 360);
  tft.drawCircle(${position.x + size.width / 2}, ${position.y + size.height / 2}, ${Math.min(size.width, size.height) / 2 - 5}, ${hexToRgb565(properties.color || '#0EA5E9')});
  // Add gauge fill logic here`;

        case 'container':
            return `  // Container Widget
  tft.fillRoundRect(${position.x}, ${position.y}, ${size.width}, ${size.height}, ${properties.borderRadius || 0}, ${hexToRgb565(properties.backgroundColor || '#FFFFFF')});
  tft.drawRoundRect(${position.x}, ${position.y}, ${size.width}, ${size.height}, ${properties.borderRadius || 0}, TFT_LIGHTGREY);`;

        default:
            return `  // Unknown widget type: ${type}`;
    }
}

function hexToRgb565(hex: string): string {
    // Convert hex color to RGB565 format for TFT displays
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);

    const rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
    return `0x${rgb565.toString(16).toUpperCase().padStart(4, '0')}`;
}

export function generateProjectFiles(widgets: Widget[], device: DeviceConfig, projectName: string) {
    const mainCode = generateEmbeddedCode(widgets, device);

    const readme = `# ${projectName}

Generated IoT GUI for ${device.name}

## Hardware Requirements
- ESP32-S3 with TFT display
- TFT_eSPI library
- SD card (optional)

## Installation
1. Install the TFT_eSPI library in Arduino IDE
2. Configure TFT_eSPI for your display in User_Setup.h
3. Upload this code to your ESP32-S3
4. The UI will appear on the display

## Widget Count: ${widgets.length}
- Display Resolution: ${device.width}x${device.height}px

Generated by IoT GUI Builder
`;

    const platformio = `[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
    bodmer/TFT_eSPI@^2.5.0
monitor_speed = 115200
`;

    return {
        'main.ino': mainCode,
        'README.md': readme,
        'platformio.ini': platformio,
        'project.json': JSON.stringify({
            name: projectName,
            device,
            widgets,
            generatedAt: new Date().toISOString()
        }, null, 2)
    };
}